readingDataPointsFilters:
  - RandomSamplingDataPointsFilter:
      prob: 0.8

referenceDataPointsFilters:
  - SurfaceNormalDataPointsFilter:
      knn: 10
      keepNormals: 1

matcher:
  KDTreeMatcher:
    knn: 1
    epsilon: 0 

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.9

errorMinimizer:
  PointToPointErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 40
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.05
      minDiffTransErr: 0.1
      smoothLength: 4 

inspector:
 VTKFileInspector:
    baseFileName: pointmatcher-run1
    dumpPerfOnExit: 0
    dumpStats: 0
    dumpIterationInfo: 0
    dumpDataLinks: 0
    dumpReading: 0
    dumpReference: 0

logger:
  FileLogger
