referenceDataPointsFilters:
  - RandomSamplingDataPointsFilter:
            prob: 0.8

referenceDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:
      knn: 5
  - RandomSamplingDataPointsFilter:
            prob: 0.5

matcher:
  KDTreeMatcher:
    knn: 1
    epsilon: 4 

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.9

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 40
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.05
      minDiffTransErr: 0.1
      smoothLength: 4 

inspector:
  VTKFileInspector:
     baseFileName : vissteps
     dumpDataLinks : 0
     dumpReading : 0
     dumpReference : 0

logger:
  FileLogger
